---
title: "p8105_hw2_ms6358"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```


## data cleaning

```{r}
litters_data = read_excel("data/Trash-Wheel-Collection-Totals-7-2021-sept.xlsx", "Mr. Trash Wheel")
drop_na(litters_data)
litters_clean_names = janitor::clean_names(litters_data)
names(litters_clean_names)
   drop_na(litters_clean_names, dumpster)
   sports_balls_round = c(pull(litters_clean_names, sports_balls))
   round(sports_balls_round , digits = 0)
```
## Read and clean precipitation data for 2018 and 2019

```{r}
litter_data_18 = read_excel("data/Trash-Wheel-Collection-Totals-7-2021-sept.xlsx","2018 Precipitation",
                            skip = 2)%>%
  janitor::clean_names() %>%
  drop_na(litter_data_18) %>%
litter_data_18

  mutate(
    litter_data_18,
     year = 2018
  )


litter_data_19 = read_excel("data/Trash-Wheel-Collection-Totals-7-2021-sept.xlsx","2019 Precipitation",
                            skip = 2)%>%
  janitor::clean_names() %>%
  drop_na(litter_data_19) %>%
  mutate(
    litter_data_19,
     year = 2019
  )

total_data = 
  left_join(litter_data_18, litter_data_19, by = "Month")
rlang::last_error()
```

## Problem 2

```{r}
pols_df =
  read_csv("./data/__MACOSX/fivethirtyeight_datasets/._pols-month.csv") %>%
  janitor::clean_names() %>%
  seperate(mon, into = c("year", "month", "day"), )
  
  
  
```